# docker-compose.yml

version: '3.8'

services:
  web:
    container_name: fast_api_boiler
    build:
      context: .
      args:
          REQUIREMENTS_FILE: reqs.txt
    command: uvicorn app.main:app --port 8000 --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
