name: Build Docker Images

on:
  push:
    branches: [main, master]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'reqs.txt'
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # 1. Сначала настраиваем правильный драйвер Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        install: true
        
    # 2. Логинимся в Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    # 3. Собираем и пушим образ с кэшированием
    - name: Build and push web image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fast_api_boiler:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64  # Явно указываем платформу
    
    # 4. Собираем остальные образы (без кэширования)
    - name: Build other images
      run: |
        docker-compose build postgres prometheus tempo grafana