name: Build Docker Images

on:
  push:
    branches: [ main, master ]  # Триггер на пуш в main/master
    paths:  # Триггер только при изменении важных файлов
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'reqs.txt'
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push web image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fast_api_boiler:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and cache other images
      run: |
        docker-compose -f docker-compose.yml build postgres prometheus tempo grafana