name: Build Docker Images

on:
  push:
    branches: [main, master]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'requirements/**' 
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push web image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fast_api_boiler:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          REQUIREMENTS_FILE=reqs.txt