name: Deploy to Render

on:
  push:
    branches: [main, master]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Render CLI
        run: |
          curl -fsSL https://cli.render.com/install.sh | bash

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_NAME: Ci-CD2
        run: |
          render services deploy $RENDER_SERVICE_NAME --wait