name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pipx install poetry

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run tests
      env:
        # Обязательные настройки
        SECRET_KEY: "dummy-secret-key-for-tests"
        ALGORITHM: "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES: "30"
        
        # Настройки почты
        EMAIL_SENDER: "noreply@test.com"
        SMTP_SERVER: "smtp.test.com"
        SMTP_PORT: "587"
        SMTP_USERNAME: "user@test.com"
        SMTP_PASSWORD: "password"
        
        # Настройки базы данных (должны совпадать с service postgres выше)
        POSTGRES_USER: "test_user"
        POSTGRES_PASSWORD: "test_pass"
        POSTGRES_HOST: "localhost"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "test_db"
        
        # Дополнительные настройки (если есть в вашем Settings)
        FIRST_SUPERUSER: "admin@test.com"
        FIRST_SUPERUSER_PASSWORD: "password"
        USERS_OPEN_REGISTRATION: "True"
        
        # Настройки для тестов
        TESTING: "True"
        PYTHONPATH: "${{ github.workspace }}"
        
      run: |
        poetry run pytest --cov -v